services:
  - type: web
    name: wildfire-risk-api
    env: python
    pythonVersion: "3.12"
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    workingDir: backend
    autoDeploy: true
