services:
  - type: web
    name: wildfire-risk-api
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn app:app"
    workingDir: backend
    autoDeploy: true
